const dataArray = [
	{
		key: '1',
		name: 'Cheese Pizza',
		img: '/img/1.jpeg',
		price: 20,
		currency: ' USD',
		quantity: 1,
	},
	{
		key: '2',
		name: 'Vegetable Pizza',
		img: '/img/2.png',
		price: 15.5,
		currency: ' USD',
		quantity: 1,
	},
	{
		key: '3',
		name: 'Cheese Pizza with olive',
		img: '/img/3.jpeg',
		price: 11.2,
		currency: ' USD',
		quantity: 1,
	},
	{
		key: '4',
		name: 'Paparoni Pizza',
		img: '/img/4.jpeg',
		price: 20.3,
		currency: ' USD',
		quantity: 1,
	},
	{
		key: '5',
		name: 'Paparoni Cheese Pizza',
		img: '/img/5.jpeg',
		price: 24,
		currency: ' USD',
		quantity: 1,
	},
	{
		key: '6',
		name: 'Plain Cheese Pizza',
		img: '/img/1.jpeg',
		price: 22,
		currency: ' USD',
		quantity: 1,
	},
];
export default dataArray;
