const dataArray = [
  {
    key: "1",
    name: "Cheese ",
    img: "/img/1.jpeg",
    price: 20,
    quantity: 1,
  },
  {
    key: "2",
    name: "Vegetable ",
    img: "/img/2.png",
    price: 10,
    quantity: 1,
  },
  {
    key: "3",
    name: "Cheese  with olive",
    img: "/img/3.jpeg",
    price: 12.5,
    quantity: 1,
  },
  {
    key: "4",
    name: "Paparoni ",
    img: "/img/4.jpeg",
    price: 20.5,
    quantity: 1,
  },
  {
    key: "5",
    name: "Paparoni Cheese ",
    img: "/img/5.jpeg",
    price: 24,
    quantity: 1,
  },
  {
    key: "6",
    name: "Plain Cheese",
    img: "/img/1.jpeg",
    price: 22,
    quantity: 1,
  },
  {
    key: "7",
    name: "Cheese",
    img: "/img/6.webp",
    price: 25,
    quantity: 1,
  },
  {
    key: "8",
    name: "Cheese Burst",
    img: "/img/7.jpg",
    price: 55,
    quantity: 1,
  },
  {
    key: "9",
    name: "Wave of Cheese",
    img: "/img/8.jpg",
    price: 48,
    quantity: 1,
  },
  {
    key: "10",
    name: "Cheesy Delight",
    img: "/img/9.jpg",
    price: 42,
    quantity: 1,
  },
  {
    key: "11",
    name: "Italiano",
    img: "/img/10.jpg",
    price: 28,
    quantity: 1,
  },
  {
    key: "12",
    name: "Mexican Green Wave",
    img: "/img/11.jpg",
    price: 35,
    quantity: 1,
  },
  {
    key: "13",
    name: "Veggie Delight",
    img: "/img/12.jpg",
    price: 47,
    quantity: 1,
  },
  {
    key: "14",
    name: "Paneer Tikka",
    img: "/img/13.jpg",
    price: 55,

    quantity: 1,
  },
  {
    key: "15",
    name: "Olive Cheese",
    img: "/img/14.jpg",
    price: 65,

    quantity: 1,
  },
  {
    key: "16",
    name: "Hot & Spicy",
    img: "/img/15.jpg",
    price: 38,

    quantity: 1,
  },
  {
    key: "17",
    name: "Hawaiian",
    img: "/img/16.jpg",
    price: 34,

    quantity: 1,
  },
];
export default dataArray;
