const dataArray = [
	{
		key: '1',
		name: 'Cheese ',
		img: '/img/1.jpeg',
		price: 20,
		currency: ' USD',
		quantity: 1,
	},
	{
		key: '2',
		name: 'Vegetable ',
		img: '/img/2.png',
		price: 10,
		currency: ' USD',
		quantity: 1,
	},
	{
		key: '3',
		name: 'Cheese  with olive',
		img: '/img/3.jpeg',
		price: 12.5,
		currency: ' USD',
		quantity: 1,
	},
	{
		key: '4',
		name: 'Paparoni ',
		img: '/img/4.jpeg',
		price: 20.5,
		currency: ' USD',
		quantity: 1,
	},
	{
		key: '5',
		name: 'Paparoni Cheese ',
		img: '/img/5.jpeg',
		price: 24,
		currency: ' USD',
		quantity: 1,
	},
	{
		key: '6',
		name: 'Plain Cheese ',
		img: '/img/1.jpeg',
		price: 22,
		currency: ' USD',
		quantity: 1,
	},
];
export default dataArray;
